target 'ZLSwipeableViewSwiftDemo' do
	pod 'UIColor+FlatColors'
	pod 'Cartography'
	# pod 'ReactiveUI'
end

target 'ZLSwipeableViewSwiftDemoTests' do
	pod 'UIColor+FlatColors'
	pod 'Cartography'
	# pod 'ReactiveUI'
end

use_frameworks!
