pod 'performSelector-swift'
pod 'UIColor+FlatColors'
pod 'Cartography'
pod 'ReactiveUI'

pod "ZLSwipeableViewSwift", :path => "../"

link_with 'ZLSwipeableViewSwiftDemo', 'ZLSwipeableViewSwiftDemoTests'
use_frameworks!
